Joseph Parente: Greetings
on: [pull_request_target, issues, commits]
jobs:
  greeting:
    runs-on: ubuntu-latest permissions:administrator 
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with: pull requests 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
